{
  "formatVersion": "1.1",
  "component": {
    "group": "com.draftsmith",
    "module": "draftsmith",
    "version": "1.0.0+26.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "draftsmith-1.0.0+26.2.jar",
          "url": "draftsmith-1.0.0+26.2.jar",
          "size": 180458,
          "sha512": "73bba86c85d40bd2926897864e38c81229a07c6633e99c47d83a01fbf94aec867aa5ee687eadeeda3e45bc4d8c3a4284743ffecadea9dac1e784d3e082cb22bc",
          "sha256": "9fe0239ce6f2f803df34ade54d3e7343f23a1f2ec6eb91cfb43e03609ed09397",
          "sha1": "6bcd201db0c0a79d04ebb2413c19d9a78b4a947a",
          "md5": "b582f5e3aef927bfa262882c59876429"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.153.0+26.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "2.1.0+26.2"
          }
        }
      ],
      "files": [
        {
          "name": "draftsmith-1.0.0+26.2.jar",
          "url": "draftsmith-1.0.0+26.2.jar",
          "size": 180458,
          "sha512": "73bba86c85d40bd2926897864e38c81229a07c6633e99c47d83a01fbf94aec867aa5ee687eadeeda3e45bc4d8c3a4284743ffecadea9dac1e784d3e082cb22bc",
          "sha256": "9fe0239ce6f2f803df34ade54d3e7343f23a1f2ec6eb91cfb43e03609ed09397",
          "sha1": "6bcd201db0c0a79d04ebb2413c19d9a78b4a947a",
          "md5": "b582f5e3aef927bfa262882c59876429"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "draftsmith-1.0.0+26.2-sources.jar",
          "url": "draftsmith-1.0.0+26.2-sources.jar",
          "size": 133295,
          "sha512": "b48ab6b5d7b9ce0337a0d3441937b681855bc074bbdbdc15ff9fbc4f62740c59ce46e8713d38f8b09e4d380fc0f36aa3e2b0b99cc7ed7b0dc6f5396342546b0a",
          "sha256": "94b6eae16071d66a15e3c54b04000f4ffac03f4ac5fe7de226fae3e0933ab064",
          "sha1": "b41765255cf5c158eefae4a8f68b3a3b6fb45165",
          "md5": "59b68812e36c920020555f60a01d10e0"
        }
      ]
    }
  ]
}
