{
  "formatVersion": "1.1",
  "component": {
    "group": "com.draftsmith",
    "module": "draftsmith",
    "version": "1.0.1+26.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "draftsmith-1.0.1+26.1.2.jar",
          "url": "draftsmith-1.0.1+26.1.2.jar",
          "size": 184122,
          "sha512": "9de6bc11c1d545d49f1670447d0c6fea17ee0709f94ee9a369b9118b384f2a0cfc85548110fa507f76c72a157e5357a1ac4e42fe69465ef6be05e852b64cbd57",
          "sha256": "f1a1450410a5b28eae8422442c30da6e1171188b88f497086c85b927e898e22c",
          "sha1": "3583e22aca8363e45b8eb61359f7ea0e99900650",
          "md5": "722c93582ba510f2d6110751021950fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.145.4+26.1.2"
          }
        },
        {
          "group": "eu.pb4",
          "module": "sgui",
          "version": {
            "requires": "2.0.0+26.1"
          }
        }
      ],
      "files": [
        {
          "name": "draftsmith-1.0.1+26.1.2.jar",
          "url": "draftsmith-1.0.1+26.1.2.jar",
          "size": 184122,
          "sha512": "9de6bc11c1d545d49f1670447d0c6fea17ee0709f94ee9a369b9118b384f2a0cfc85548110fa507f76c72a157e5357a1ac4e42fe69465ef6be05e852b64cbd57",
          "sha256": "f1a1450410a5b28eae8422442c30da6e1171188b88f497086c85b927e898e22c",
          "sha1": "3583e22aca8363e45b8eb61359f7ea0e99900650",
          "md5": "722c93582ba510f2d6110751021950fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "draftsmith-1.0.1+26.1.2-sources.jar",
          "url": "draftsmith-1.0.1+26.1.2-sources.jar",
          "size": 135897,
          "sha512": "6baba9c0e04e51433e5f6eef0acf24aa2af7e4306a33ee3a6070ae320362f84719a739439a357ac0a0ed6bc9f99c557c39d12c814a23b2886b1c51dcb689d860",
          "sha256": "6eb198ef02e1f3aa9b494dd717be0860455bd02ce221e6fd53aba1096975cc97",
          "sha1": "007f5ba5fa0735b5a81fb9cf8060154fcd1f6143",
          "md5": "5803f27f27edd12ef30134d8e11154e0"
        }
      ]
    }
  ]
}
